#!/usr/bin/env ruby

# Put all our core library files in the require path
$:.unshift(File.expand_path(File.join(File.dirname(__FILE__), 'lib')))

require 'core'

options = {}
OptionParser.new do |opts|
  opts.banner = "Usage: #{__FILE__} [options]"

  opts.separator Paint["\nGeneral Options: ", '#95a5a6']
  opts.on("-v", "--verbose", "Run verbosely") do |v|
    options[:verbose] = v
  end
  # directory flag
  opts.on("-d DIR", "--dir DIR", String, "Upload files in DIR") do |d|
    options[:directory] = d unless d.nil?
  end

  opts.on('-h', '--help', 'Show this help message') do
    puts opts
    exit
  end
end.parse!

if Upto::Utils.is_first_run?
  puts "First run"
end

result_url = ''
uploader = Upto::Transport::Uploader.new(options[:directory]) unless options[:directory].nil?
uploader = Upto::Transport::Uploader.new(Dir.pwd) if options[:directory].nil?


Whirly.start(spinner: "toggle8", status: "Uploading files (#{uploader.total_files} total)") do
  beginning_time = Time.now
  sleep 1  # Just to see the spinner if the files are small
  result_url = uploader.upload!(options[:verbose])  # Do the file upload

  Whirly.status = "Done!\n"
  Clipboard.copy(result_url)
  print Paint["Your url is: #{result_url} (copied to clipboard) ", :bold]
  puts Paint["[#{((Time.now - beginning_time)).round(2)}s]", "#95a5a6"]
end
