#!/usr/bin/env ruby

# Put all our core library files in the require path
$:.unshift(File.expand_path(File.join(File.dirname(__FILE__), 'lib')))

require 'core'

result_url = ''
uploader = Upto::Transport::Uploader.new('.')


Whirly.start(spinner: "dots", status: "Uploading files (#{uploader.total_files} total)") do
  beginning_time = Time.now
  sleep 1  # Just to see the spinner if the files are small
  result_url = uploader.upload!  # Do the file upload

  Whirly.status = "Done!\n"
  Clipboard.copy(result_url)
  print Paint["Your url is: #{result_url} (copied to clipboard) ", :bold]
  puts Paint["[#{((Time.now - beginning_time)).round(2)}s]", "#95a5a6"]
end
